---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      - URL=domain.com
      - VALIDATION=http
      - EMAIL=mail@mail.com
      - ONLY_SUBDOMAINS=false
      - STAGING=false #optional
    volumes:
      - /home/rterrero/nginx_letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
